### ISSUE TITLE
A question about ts-PSW

### ISSUE THREAD

**Issue by xichaoqiang** [sergiventosa/ts-PWS#3]
Dear Sergi,

I found your ts-PWS work to be very intriguing. I have a question regarding the use of the 

exp(2𝑗𝜋𝑓𝑡) term in the continuous wavelet transform (CWT). Is this term still necessary for ts-PWS?

I noticed that this term is used in the S-transform for tf-PWS.

Attached below is the figure generated by my code:

![image](https://github.com/sergiventosa/ts-PWS/assets/30900789/dd11268e-078b-48bf-9831-b3bd56d103eb)

Best regards,

**Comment by sergiventosa** [comment]
Dear Xichaoqiang,

The exp(2𝑗𝜋𝑓𝑡) term you introduce in your (matlab) code would be necessary only if you want to implement the tf-PWS using the wavelet transform, by applying the relationship between the (Morlet) CWT and the ST. However, as I show in (Ventosa et al., 2017) and you can see in the C code, we can compute the phase coherence from the (pseudo-)analytic wavelet transform of the data sequence directly because this term is constant, i.e., independent of the data.

I hope this solves your doubt.

Best,
Sergi

**Comment by xichaoqiang** [comment]
Dear Sergi,

Thank you for your detailed explanation. I now understand why the exp(2𝑗𝜋𝑓𝑡) term is unnecessary for computing the phase coherence using the (pseudo-)analytic wavelet transform. I have reviewed the referenced C code and Ventosa et al. (2017) as well, which have clarified the implementation further.

Your guidance has been very helpful in resolving my doubt.

Best regards,
Xichaoqiang
